global_costmap:
  global_frame: /map
  robot_base_frame: /base_footprint
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: true
  transform_tolerance: 0.5
  plugins:
    -
      name: static_layer
      type: costmap_2d::StaticLayer
    -
      name: hard_layer
      type: costmap_2d::HardLayer
    -
      name: inflation_layer
      type: costmap_2d::InflationLayer

  static_layer:
    map_topic: /slam/map
    unknown_cost_value: 51
    lethal_cost_threshold: 61
    # true to enable the patches
    subscribe_to_updates: true
    # The topics for the soft and hard obstacle patches to the static map
    #soft_obstacles_topic: /data_fusion/soft_obstacles_patch
    #hard_obstacles_topic: /data_fusion/hard_obstacles_patch

  hard_layer:
    map_topic: /data_fusion/soft_obstacles_patch
    unknown_cost_value: 51
    lethal_cost_threshold: 61

  inflation_layer:
    inflation_radius: 0.6
    cost_scaling_factor: 7.0
