controller_frequency: 5.0

base_local_planner: eband_local_planner/EBandPlannerROS

EBandPlannerROS:
  Ctrl_Rate: 5.0
  differential_drive: True
  max_acceleration: 0.5
  max_lin_vel: 0.2
  max_vel_th: 0.4
  min_vel_lin: 0.01
  min_vel_theta: 0.0
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.2
  disallow_hysteresis: False
