global_costmap:
  global_frame: /map
  robot_base_frame: /base_footprint
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: true
  transform_tolerance: 0.5
  track_unknown_space: false
  robot_radius: 0.47
  footprint: [[-0.235, -0.17], [-0.235, 0.17], [0.235, 0.17], [0.235, -0.17]]
  footprint_padding: 0.01

  # Static Layer receives the map from SLAM, updateWithTrueOverwrite
  plugins:
    - name: static_layer
      type: costmap_2d::StaticLayer
    - name: inflation_layer
      type: costmap_2d::InflationLayer

  static_layer:
    map_topic: /slam/map
    unknown_cost_value: 51
    lethal_cost_threshold: 61
    subscribe_to_updates: false
    trinary_costmap: true

  inflation_layer:
    inflation_radius: 0.5
    cost_scaling_factor: 7.0
