robot:
  robot_specifications:
    - footprint:
        footprint_specifications:
          radius: 0.47
          points:
            - point:
                x: 0.235
                y: 0.170
            - point:
                x: 0.235
                y: -0.170
            - point:
                x: -0.235
                y: -0.170
            - point:
                x: -0.235
                y: 0.170
    - initial_pose:
        x: 0
        y: 0
        theta: 0
    - laser:
        laser_specifications:
          max_angle: 2.356194
          min_angle: -2.356194
          max_range: 4
          min_range: 0
          num_rays: 270
          frequency: 10
          frame_id: laser_0
          pose:
            x: 0.1400000005960464
            y: 0
            theta: 0
          noise:
            noise_specifications:
              noise_mean: 0
              noise_std: 0
