controller_frequency: 5.0

base_local_planner: rsband_local_planner/RSBandPlannerROS

RSBandPlannerROS:
  stop: False
  rear_steering_modes: [&none 0, &counter 1, &crab 2, &hybrid 3]
  rear_steering_mode: *counter
  max_speed: 0.2
  max_steering_angle: 0.4
  wheelbase: 0.32
  emergency_planning: True

  # reeds shepp planner params
  eband_to_rs_strategies: [&start_to_end 0, &start_to_next 1, &point_to_point 2, &skip_failures 3, &start_to_receding_end 4]
  eband_to_rs_strategy: *start_to_next
  max_planning_duration: 0.05
  valid_state_max_cost: 0
  state_checking_modes: [&center 0, &footprint 1]
  state_checking_mode: *center
  interpolation_num_poses: 20
  allow_unknown: False
  display_planner_output: False

  # car like fuzzy path tracking controller params
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.2
  goal_dist_threshold: 0.2
  lateral_deviation_tolerance: 0.05
  update_sub_goal_dist_threshold: 0.6
  display_controller_io: False

  # eband params
  eband_min_relative_bubble_overlap_: 0.3
  eband_tiny_bubble_distance: 0.01
  eband_tiny_bubble_expansion: 0.01
  eband_internal_force_gain: 1.0
  eband_external_force_gain: 2.0
  num_iterations_eband_optimization: 5
  eband_equilibrium_approx_max_recursion_depth: 5
  eband_equlibrium_relative_overshoot: 0.75
  eband_significant_force_lower_bound: 0.10
  costmap_weight: 20.0
