robot_base_frame: /base_footprint
footprint: [[-0.235, -0.17], [-0.235, 0.17], [0.235, 0.17], [0.235, -0.17]]
robot_radius: 0.29
footprint_padding: 0.01

update_frequency: 2.0
publish_frequency: 1.0
transform_tolerance: 1.0
resolution: 0.04
track_unknown_space: true

static_layer:
  map_topic: /slam/map
  subscribe_to_updates: true

obstacle_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {data_type: LaserScan, topic: /laser/scan, marking: true, clearing: true, inf_is_valid: true}
  obstacle_range: 3.0
  raytrace_range: 4.0

inflation_layer:
  cost_scaling_factor: 10.0
  inflation_radius: 0.3
