controller_frequency: 5.0

base_local_planner: teb_local_planner/TebLocalPlannerROS

TebLocalPlannerROS:
  odom_topic: odom
  map_frame: /odom

  # Trajectory

  teb_autosize: True
  dt_ref: 0.5
  dt_hysteresis: 0.15
  global_plan_overwrite_orientation: True
  global_plan_viapoint_sep: -0.1
  force_reinit_new_global_dist: 1.0
  max_global_lookahead_dist: 4.0
  feasibility_check_no_poses: 8
  shrink_horizon_backup: False
  publish_feedback: False

  # Robot

  max_vel_x: 0.2
  max_vel_x_backwards: 0.15
  max_vel_theta: 0.5
  acc_lim_x: 0.5
  acc_lim_theta: 0.5
  min_turning_radius: 0.5
  wheelbase: 0.32
  cmd_angle_instead_rotvel: False
  footprint_model:
    # type: circular
    # radius: 0.235
    # type: polygon
    # vertices:
      # - [0.235,0.17]
      # - [0.235,-0.17]
      # - [-0.235,-0.17]
      # - [-0.235,0.17]
    type: two_circles
    front_offset: 0.156
    front_radius: 0.156
    rear_offset: 0.156
    rear_radius: 0.156

  # GoalTolerance

  xy_goal_tolerance: 0.3
  yaw_goal_tolerance: 0.2
  free_goal_vel: False

  # Obstacles

  min_obstacle_dist: 0.15
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 0.3
  obstacle_poses_affected: 20

  # Optimization

  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.1
  weight_max_vel_x: 2
  weight_max_vel_theta: 1
  weight_acc_lim_x: 0
  weight_acc_lim_theta: 0
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 1
  weight_kinematics_turning_radius: 50
  weight_optimaltime: 1
  weight_obstacle: 50
  weight_viapoint: 0

  # Homotopy Class Planner

  enable_homotopy_class_planning: True
  enable_multithreading: True
  max_number_classes: 4
  selection_cost_hysteresis: 0.5
  h_signature_prescaler: 1.0 # 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: False
