controller_frequency: 5.0

base_local_planner: teb_local_planner/TebLocalPlannerROS

TebLocalPlannerROS:
  odom_topic: odom
  map_frame: /odom

  # Trajectory

  teb_autosize: True
  dt_ref: 1.0
  dt_hysteresis: 0.1
  min_samples: 3
  global_plan_overwrite_orientation: False
  force_reinit_new_global_dist: 1.0
  max_global_lookahead_dist: 3.0
  feasibility_check_no_poses: 5
  shrink_horizon_backup: False
  publish_feedback: False

  # Robot

  max_vel_x: 0.2
  max_vel_x_backwards: 0.2
  max_vel_theta: 1.0
  acc_lim_x: 1.0
  acc_lim_theta: 2.0
  min_turning_radius: 0.35
  wheelbase_: 0.32
  cmd_angle_instead_rotvel: false
  footprint_model:
    type: circular
    radius: 0.47
    # type: polygon
    # vertices:
      # - [0.235,0.17]
      # - [0.235,-0.17]
      # - [-0.235,-0.17]
      # - [-0.235,0.17]

  # GoalTolerance

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  free_goal_vel: False

  # Obstacles

  min_obstacle_dist: 0.4
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 30
  costmap_converter_plugin: ""
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5
  costmap_obstacles_front_only: False
  costmap_emergency_stop_dist: 0.5

  # Optimization

  no_inner_iterations: 5
  no_outer_iterations: 5
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.1
  weight_max_vel_x: 2
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 1
  weight_kinematics_turning_radius: 1
  weight_optimaltime: 1
  weight_obstacle: 50
  weight_dynamic_obstacle: 10
  alternative_time_cost: False

  # Homotopy Class Planner

  enable_homotopy_class_planning: False
  enable_multithreading: True
  max_number_classes: 5
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 1.0
  h_signature_threshold: 0.1
  obstacle_heading_threshold: 1.0
  visualize_hc_graph: False
